# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Java project to Azure Function App - azure-training-function

on:
  push:
    branches:
      - main
    paths:
      - 'function-app/**'
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: azure-training-function # set this to your function app name on Azure
  PACKAGE_DIRECTORY: './function-app' # set this to the directory which contains pom.xml file
  JAVA_VERSION: '17' # set this to the java version to use

jobs:
  build-and-deploy:
    runs-on: windows-latest
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: Setup Java Sdk ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'microsoft'

      - name: Build Function App
        shell: pwsh
        run: |
          pushd './${{ env.PACKAGE_DIRECTORY }}'
          mvn clean package azure-functions:package
          popd
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_2360D6EA553A4993BFC8614CFADF6FE8 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_851BD149C1C34F89901ACC2C8DDBB25E }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_CEC6C5170FCD4D888C2865F6B7612328 }}

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: 'azure-training-function'
          slot-name: 'Production'
          package: '${{ env.PACKAGE_DIRECTORY }}/target/azure-functions/${{ env.AZURE_FUNCTIONAPP_NAME }}'
          respect-pom-xml: true
          
